"""
satquery/utils/report_builder.py

Builds downloadable Markdown and PDF execution reports from controller results.

PDF fix: the original code called os.makedirs(os.path.dirname(out_path)) which
crashes when out_path has no directory component (dirname returns "").
This version checks for an empty dirname before calling makedirs.

Enhanced PDF:
- Proper 15mm margins
- multi_cell() for all text (word wrap)
- Scaled image inset
- Multi-page layout with page numbers
- Structured sections: observations, inferences, evidence, limitations
"""
from __future__ import annotations

import datetime as dt
import io
import os
from typing import Optional

from fpdf import FPDF
from PIL import Image as PILImage


def build_markdown_report(query: str, result_dict: dict) -> str:
    """Build a Markdown report from an analysis result."""
    timestamp = dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# SatQuery AI — Analysis Report",
        f"*Generated: {timestamp}*",
        "",
        "---",
        "",
        f"**Query:** {query}",
        f"**Analysis Type:** {result_dict.get('task', '').replace('_', ' ').title()}",
        "",
        "## Answer",
        result_dict.get("answer", "No answer available."),
        "",
    ]

    if result_dict.get("observations"):
        lines.append("## Observations")
        for obs in result_dict["observations"]:
            lines.append(f"- {obs}")
        lines.append("")

    if result_dict.get("inferences"):
        lines.append("## Inferences")
        for inf in result_dict["inferences"]:
            lines.append(f"- {inf}")
        lines.append("")

    ev = result_dict.get("evidence_strength", "limited")
    lines += [f"**Evidence Strength:** {ev.capitalize()}", ""]

    if result_dict.get("limitations"):
        lines.append("## Limitations")
        for lim in result_dict["limitations"]:
            lines.append(f"- {lim}")
        lines.append("")

    lines.append("## Technical Details")
    lines.append(f"- **Tools used:** {', '.join(result_dict.get('tools_used', [])) or 'none'}")
    lines.append(f"- **Models used:** {', '.join(result_dict.get('models_used', [])) or 'none'}")
    lines.append(f"- **Processing time:** {result_dict.get('processing_time_ms', 0)} ms")

    if result_dict.get("warnings"):
        lines += ["", "## Warnings"]
        for w in result_dict["warnings"]:
            lines.append(f"- ⚠️ {w}")

    lines += [
        "",
        "---",
        "*Report generated by SatQuery AI — ISRO/SAC SIH Problem Statement 26167*",
    ]
    return "\n".join(lines)


class _SatQueryPDF(FPDF):
    """Custom FPDF subclass with header and footer."""

    def __init__(self):
        super().__init__()
        self.set_margins(15, 20, 15)  # left, top, right (mm)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(30, 80, 160)
        self.cell(0, 8, "SatQuery AI -- Analysis Report", align="L", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.set_draw_color(30, 80, 160)
        self.set_line_width(0.5)
        self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 8, f"Page {self.page_no()} | ISRO/SAC SIH Problem Statement 26167", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 80, 160)
        self.ln(4)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.set_draw_color(200, 200, 200)
        self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        # Replace problematic unicode characters with ASCII equivalents
        clean = (text or "").encode("latin-1", errors="replace").decode("latin-1")
        self.multi_cell(0, 6, clean, new_x="LMARGIN", new_y="NEXT")

    def bullet_list(self, items: list[str]):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        for item in items:
            clean = ("• " + item).encode("latin-1", errors="replace").decode("latin-1")
            self.multi_cell(0, 6, clean, new_x="LMARGIN", new_y="NEXT")

    def kv_row(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(80, 80, 80)
        key_clean = key.encode("latin-1", errors="replace").decode("latin-1")
        self.cell(45, 6, key_clean)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        val_clean = str(value).encode("latin-1", errors="replace").decode("latin-1")
        self.multi_cell(0, 6, val_clean, new_x="LMARGIN", new_y="NEXT")

    def embed_image(self, pil_image: PILImage.Image, caption: str = ""):
        """Embed a PIL image in the PDF, scaled to fit page width."""
        try:
            buf = io.BytesIO()
            pil_image.save(buf, format="JPEG", quality=85)
            buf.seek(0)
            max_w = self.w - 30  # page width minus margins
            img_w, img_h = pil_image.size
            scale = min(max_w / img_w, 80 / (img_h * max_w / img_w))  # max 80mm height
            display_w = min(max_w, img_w * scale)
            display_h = img_h * (display_w / img_w)
            x = (self.w - display_w) / 2
            self.image(buf, x=x, y=None, w=display_w, h=display_h)
            if caption:
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(100, 100, 100)
                self.cell(0, 5, caption, align="C", new_x="LMARGIN", new_y="NEXT")
        except Exception as e:
            self.body_text(f"[Image could not be embedded: {e}]")


def build_pdf_report(
    query: str,
    result_dict: dict,
    out_path: str,
    image_pil: Optional[PILImage.Image] = None,
) -> str:
    """
    Build a PDF report and write to out_path.

    Args:
        query: The user's query string
        result_dict: The analysis result dictionary
        out_path: Output file path (directory will be created if needed)
        image_pil: Optional PIL Image to embed

    Returns:
        out_path on success.
    """
    # ── Fix: only makedirs if there's a real directory ──
    dir_path = os.path.dirname(out_path)
    if dir_path:
        os.makedirs(dir_path, exist_ok=True)

    timestamp = dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    pdf = _SatQueryPDF()
    pdf.add_page()

    # ── Title block ──
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(10, 40, 100)
    pdf.cell(0, 12, "SatQuery AI", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, "Interactive Vision-Language Assistant for Remote-Sensing Analysis",
             align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, "ISRO/SAC Problem Statement 26167 - Smart India Hackathon",
             align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)

    # ── Metadata ──
    pdf.section_title("Report Details")
    pdf.kv_row("Generated:", timestamp)
    pdf.kv_row("Query:", query)
    pdf.kv_row("Analysis Type:", result_dict.get("task", "").replace("_", " ").title())
    pdf.kv_row("Processing Time:", f"{result_dict.get('processing_time_ms', 0)} ms")

    # ── Image ──
    if image_pil is not None:
        pdf.section_title("Satellite Image")
        pdf.embed_image(image_pil, caption="Input satellite image (visualization)")

    # ── Answer ──
    pdf.section_title("AI Analysis - Answer")
    pdf.body_text(result_dict.get("answer", "No answer available."))

    # ── Observations ──
    observations = result_dict.get("observations", [])
    if observations:
        pdf.section_title("Observations")
        pdf.bullet_list(observations)

    # ── Inferences ──
    inferences = result_dict.get("inferences", [])
    if inferences:
        pdf.section_title("Inferences")
        pdf.bullet_list(inferences)

    # ── Evidence Strength ──
    pdf.section_title("Evidence Strength")
    ev = result_dict.get("evidence_strength", "limited").capitalize()
    pdf.body_text(ev)

    # ── Limitations ──
    limitations = result_dict.get("limitations", [])
    if limitations:
        pdf.section_title("Limitations")
        pdf.bullet_list(limitations)

    # ── Technical Details ──
    pdf.section_title("Technical Details")
    tools = ", ".join(result_dict.get("tools_used", [])) or "none"
    models = ", ".join(result_dict.get("models_used", [])) or "none"
    pdf.kv_row("Tools used:", tools)
    pdf.kv_row("Models used:", models)

    params = result_dict.get("parameters", {})
    if params:
        param_str = "; ".join(f"{k}: {v}" for k, v in params.items() if v is not None)
        pdf.kv_row("Parameters:", param_str)

    warnings = result_dict.get("warnings", [])
    if warnings:
        pdf.section_title("Processing Warnings")
        pdf.bullet_list(warnings)

    pdf.output(out_path)
    return out_path
